### PR TITLE
Use tabs in Dockerfile

### PR DESCRIPTION
**Pull request by szepeviktor**
Just 1 TAB.

### CODE REVIEW

**Comment by stintel** [comment]
If you plan to submit patches, at least make sure the automated check pass.

**Comment by stintel** [comment]
Finally, if you want to contribute, have a look at the format of https://github.com/stintel/vallumd/commits/master and please follow this format in your commit messages.

**Comment by szepeviktor** [comment]
Okay.
I was up to a 1 character PR.

**Comment by stintel** [comment]
I appreciate you wanting to get involved, but polluting the git history for a change like this, withouth SoB, and not following the format of all other commits in this repo, is just not good enough for me.

**Pull request closed without merging**
